Mates y empanadas
Magmabros/Draconia-splurt pull request #3
Opened 2022-07-24 03:34 UTC by FrankitoBoar

# About The Pull Request
Añade sprites del mate y un poco de codigo (porque soy un pajero) junto con los sprites de las futuras empanadas

## Why It's Good For The Game
PORQUE SON MATES MAN, SON LO MEJOR

2022-07-24 21:53 UTC, Magmabros commented
no intentes colar cosas, quita el libro y la modificacion de mapa, solo pasa el mate, a la empanada cambiale una de las sprites para que se coma desde arriba

2022-07-24 23:53 UTC, FrankitoBoar commented
no es por colarlo pedazo de pelele, es que no se como sacarlo, puta

2022-07-25 00:04 UTC, Magmabros requested changes
corrije el pr como dije en discord

2023-12-23 16:20 UTC, FrankitoBoar commented
Mi libertad de expresion fue cortada

2023-12-23 16:20 UTC, closed without merging